### ISSUE TITLE
memcpy() gotcha!

### ISSUE THREAD

**Issue by motet-a** [Arignir/chaos#8]
[In `vga.c`](https://github.com/Arignir/chaos/blob/master/arch/x86/devices/vga/vga.c#L66):

```c
static uint const	VGA_WIDTH	= 80;
static uint const	VGA_HEIGHT	= 25;
static uint16 *const	VGA_BUFFER	= (uint16*)((char *)KERNEL_VIRTUAL_BASE + 0xB8000);

memcpy(VGA_BUFFER, VGA_BUFFER + VGA_WIDTH, (VGA_HEIGHT - 1) * VGA_WIDTH * sizeof(uint16));
```

I can simplify the last line to:

```c
memcpy(VGA_BUFFER, VGA_BUFFER + 80, 3840);
```

This looks very wrong to me. The source and destination memory areas do overlap.

Why don't use `memmove()` everywhere? It is safer and nearly as fast as `memcpy()`. The confusion between `memcpy()` and `memmove()` is responsible for terrible bugs, one of the best known being [the infamous Flash Player sound bug on Linux](https://bugzilla.redhat.com/show_bug.cgi?id=638477).  Linus Torvalds himself expressed [his (rough) opinion](https://bugzilla.redhat.com/show_bug.cgi?id=638477#c132) about it in the same thread.

**Comment by Arignir** [comment]
Haha, this was done on purpose because i didn't have a `memmove()` implementation yet and didn't have the strength to add one at that moment. Don't worry, a patch is intended today.

You have a fine eye, gg!

**Comment by Arignir** [comment]
Fixed in https://github.com/Arignir/chaos/commit/5bd31894b4979bf3caece816d09504e98e8d0d0e
